### ISSUE TITLE
PredIQt alert bot ($3,500)

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/everipedia-bounties#1]
## Pre-Requisites

* Read and understand [the Mindswap documentation](https://docs.prediqt.com/advanced/mindswap)
* Learn how to work with [GraphQL](https://graphql.org/) (for DFuse public API)
* Read and understand [DFuse's GraphQL API](https://docs.dfuse.io/eosio/public-apis/reference/network-endpoints/)

## Description
A Telegram bot that allow users to subscribe to their personal data in predIQt. 

Users should be able to receive alerts (with links) when:
 - their orders are placed, partially filled or filled
 - market changes statuses (ended, resolved, disputed)
 - shares available to claim
 - shares claimed / burned

User can add multiple accounts to subscribe, you can take as an inspiration @EOSauthoritybot in telegram.

All the bot UI should be intuitive using buttons like the one we suggested as inspiration.

Must use Telegraf ( https://github.com/telegraf/telegraf ). Use Dfuse's GraphQL API for data reception.

Bot should use environment variables to allow running in Kylin (for testing purposes) & Mainnet.

---

This task will require using a database. Please use SQL. Information stored in the database will include information like:

* EOS account name
* Telegram account name
* You do NOT need to store which events the user subscribes to. Event subscriptions are all or nothing.

**Comment by ChaituVR** [comment]
Hi @kesar. Im interested in this.. Can i start working on it? 

Only question i have is predIQT's api doesn't provide a way to subscribe to these events, is there a some way using Dfuse? Should i explore more on that?

**Comment by kesar** [comment]
> Hi @kesar. Im interested in this.. Can i start working on it?
> 
> Only question i have is predIQT's api doesn't provide a way to subscribe to these events, is there a some way using Dfuse? Should i explore more on that?

Hi Chaitanya!

Yes, the best way to subscribe to these events its gonna be using dfuse, because predIQt API doesn't support streams for now. 

There is an open dfuse endpoint for kylin & mainnet. We use it in some of our bots / apis. Here you can have an example of subscribing to prediqtpedia events ( https://gist.github.com/kesar/3a522880ed9f933aadc43ce490fe9d7b ) 

Take in consideration that to gather orders fill, you will need to read the dbOps that dfuse provides 👍👍

https://eos.dfuse.eosnation.io

Let me know if you have more questions, I'm happy to help

(text copied from our chat on telegram https://t.me/epbounties/17 in case someone is not in the channel )

**Comment by ChaituVR** [comment]
Hi @kesar all the references you gave and updated descriptions make sense to me, thank you so much. i will start working on this :)

**Comment by ChaituVR** [comment]
Follow my progress at https://github.com/ChaituVR/prediqt_telegram_bot

**Comment by ChaituVR** [comment]
Thank you everipedia team :)
