### ISSUE TITLE
Mindswap limit order smart-contracts ($3,000)

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/everipedia-bounties#2]
## Pre-Requisites
* Advanced EOS development skills
* Read and understand [the Mindswap AMM documentation](https://docs.prediqt.com/advanced/mindswap)

### Contract 1 (limit order contract)

Develop a contract that allow to store limit orders between 2 different [extended assets](https://developers.eos.io/manuals/eosio.cdt/v1.7/structeosio_1_1extended__asset/?query=extended&page=1#struct-eosioextended_asset). This contract should allow partial and full fill.

When an order is filled or partially-filled, the user can then withdraw the earned asset from the smart contract. (do not do an auto-transfer)

### Contract 2 (arbitrage contract)

Develop a contract that has a method that can arbitrage between the previous limit order contract and [mindswap](https://mindswap.finance/). 

a contract similar to the flash loans ones, that can be called by a pair or by an order id from the limit order, and it will try to fill it or fail using mindswap. Something like:

action arbtrade(user, orderId, mindswapool)

for example, lets say we have an order 1 EOS - 4 IQ
arbtrade(orderId) 
  - check limit order contract to see the orderId and mindswap pool for EOS IQ, if its possible to exchange 1 EOS for >= 4 IQ. then trade is executed, otherwise fail and no cpu usage.
  - if arbitrage is successfull and there are some earnings, those will go to user 
 
arbpair(user, limitpair, mindswapool, limit)
same than arbtrade but with an iterator over the whole limit pair

---

Inspiration: https://medium.com/@pine_eth/pine-finance-an-amm-orders-engine-525fe1f1b1eb

Contracts must have a test suite build with boost similar to eosio.contracts. Please use this project as template ( https://github.com/kesar/eos-dev-template ) that uses docker + makefiles + boost unit tests.

If you complete this AND want to continue similar work, https://github.com/EveripediaNetwork/everipedia-bounties/issues/3 is another bounty that comes after this.

**Comment by Avm07** [comment]
Hello, i would like to start working on this issue. We can discuss details in telegram.

**Comment by kesar** [comment]
done: https://github.com/EveripediaNetwork/mindswap-smart-contracts 👍🏻

**Comment by Avm07** [comment]
Completed, pleasure doing business 👍
