### ISSUE TITLE
Mindswap limit order Node.js bot ($1,000)

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/everipedia-bounties#3]
> Blocked on completion of #2 

## Pre-Requisites
* Node.js programing

## Description
Create a Node.js bot that can interact with limit order contract and arbitrage.

Contracts branch: https://github.com/Avm07/mindswap-smart-contracts/tree/develop/contracts/limit
Kylin contract deployed: https://kylin.bloks.io/account/mindswaplimt

Bot should be able to place orders, withdraw and arbitrage with mindswap. It should use environment variables to allow run on Kylin & EOS Mainnet.

**Comment by epg323** [comment]
I will take this one !

**Comment by kesar** [comment]
done: https://github.com/EveripediaNetwork/Contract-Butler
