### ISSUE TITLE
Opendata price feed Oracle ($2,500)

### ISSUE THREAD

**Issue by kesar** [EveripediaNetwork/everipedia-bounties#5]
## Description

Develop an EOS smart-contract that allow to verify signatures from open data oracles. Allow set bounties per data push. Store median of last prices.

Contract should have an action where anyone can push a json string that comes from the coinbase / okex API. Contract must parse that json and validate the signatures, then store pair information in a table and calculate aggregated data (median, etc).

Entities will have an easy & documented eos table that can integrate in their products for pricing oracles. Those entities should be able to fill a bounty table transfering IQ tokens. 

There must be a configurable table to set the bounty per data push, and oracles that push the data will earn a fee per push. Contract should only allow one unique push of data, so nobody can send twice same data.

## Links 
https://prices.compound.finance/
https://api.pro.coinbase.com/oracle
https://www.okex.com/api/market/v3/oracle
https://compound.finance/docs/prices#introduction
https://github.com/compound-finance/open-oracle
https://blog.coinbase.com/introducing-the-coinbase-price-oracle-6d1ee22c7068

---
Contracts must have a test suite build with boost similar to eosio.contracts. Please you must use this project as template ( https://github.com/kesar/eos-dev-template ) that uses docker + makefiles + boost unit tests.

**Comment by JuanWilde** [comment]
Hi! I'd like to take care of this one, if possible :)

**Comment by JuanWilde** [comment]
Repo link -> https://github.com/JuanWilde/price-feed-oracle
